version: '3.7'
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: yavuz
      MYSQL_PASSWORD: yavuz_1
    networks:
      - bookstorenet


  myapp:
    image: tarikyavuzca/bookstoreapi:latest
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - bookstorenet

networks:
  bookstorenet:
    driver: bridge

